### ISSUE TITLE
用户回调期间遇到未经处理的异常

### ISSUE THREAD

**Issue by toohandsome** [zhichao281/duilib-MiniBlinkBrowser#2]
![QQ截图20190528231829](https://user-images.githubusercontent.com/46422252/58490015-f4007f80-819e-11e9-89ce-6e75437a92f3.png)

**Comment by toohandsome** [comment]
正常操作的时候，访问了一个广告页面

，关闭后就这样了  http://gp10.zhishangyunjiandd.top/ 
![QQ截图20190528232035](https://user-images.githubusercontent.com/46422252/58490160-3629c100-819f-11e9-9a14-3b4d147187e0.png)

**Comment by zhichao281** [comment]
hao d好的 这几天对于这个进行修改

**Comment by zhichao281** [comment]
问题找到了。因为之前在对淘宝网址的支付做兼容的时候	HWND hWnd = m_pManager->GetPaintWindow();wkeSetHandle(m_pWebView, hWnd);做了这个设置 然后在关闭某个标签的时候 会	wkeDestroyWebWindow(m_pWebView);//销毁wkeWebView对应的所有数据结构，包括真实窗口等。然后造成了主窗口一没，duilib就全没了。现在已经修复好了，。代码已提交

**Comment by toohandsome** [comment]
相同的问题出现在 关闭 ‘工具’ (点击子窗口的关闭)页面
